name: build and push and deploy
on:
  push:
    branches:
      - env-test

permissions:
  contents: read
  packages: write


jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'Witaj'

      - name: Uruchom Å›rodowisko docker-compose
        env:
          #DB
          POSTGRES_DB=${{secrets.POSTGRES_DB}}
          POSTGRES_USER=${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSSWORD}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge.yml --env-file .env -p local-prge up --build -d
          
