name: build and push and deploy
on:
  push:
    branches:
      - env-test
      - env-qa
      - main

permissions:
  contents: read
  packages: write


jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted
    environment: ${{github.ref_name}}

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'Witaj'

      - name: Uruchom Å›rodowisko docker-compose
        env:
          ENV_NAME: ${{github.ref_name}}
          POSTGRES_PORT: ${{secrets.POSTGRES.PORT}}
          #DB
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSSWORD}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge.yml -p remote-prge up --build -d
          
